# Generated by Django 2.2 on 2019-05-06 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('mbid', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('mbid', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('artist', models.ManyToManyField(to='info.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackTally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_on', models.DateTimeField()),
                ('count', models.IntegerField(default=0)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_track_tally', related_query_name='user_track_tally', to='info.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_tally', related_query_name='track_tally', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
