# Generated by Django 2.2 on 2019-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertracktally',
            name='played_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
